### ISSUE TITLE
Error Handling when loading a Player

### ISSUE THREAD

**Issue by Sebbenbear** [The-Team-Awesome/Zompocalypse#1]
Get the following exception when I load a .png when I load a player - needs to handle errors and allow the player to try again.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at zompocalypse.datastorage.Loader.LoadFile(Loader.java:78)
    at zompocalypse.ui.appwindow.MainFrame.loadCharacter(MainFrame.java:222)
    at zompocalypse.ui.appwindow.MainFrame.processCommand(MainFrame.java:174)
    at zompocalypse.controller.MenuListener.actionPerformed(MenuListener.java:25)

**Comment by thomsedavi** [comment]
I done fixed this up good. Now has a pop up error message if Player fails to load for whatever reason.

**Comment by Sebbenbear** [comment]
Nice :dancer:
