### ISSUE TITLE
Couldn't load player

### ISSUE THREAD

**Issue by Sebbenbear** [The-Team-Awesome/Zompocalypse#7]
Saved Amy in the game, quit the application, opened the application, loaded the player.

Got the following exception:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
    at zompocalypse.datastorage.Loader.LoadFile(Loader.java:78)
    at zompocalypse.ui.appwindow.MainFrame.loadCharacter(MainFrame.java:222)
    at zompocalypse.ui.appwindow.MainFrame.processCommand(MainFrame.java:174)
    at zompocalypse.controller.MenuListener.actionPerformed(MenuListener.java:25)
    at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)

**Comment by thomsedavi** [comment]
Did you Refresh after you did this? Project needs to be Refreshed when a Player or Map is saved, not sure if there is a way to do this automatically.

**Comment by Sam-Costigan** [comment]
Yeah files to be loaded need to be saved in the projects assets folder. I'm not sure if there is any way around this, since if Eclipse doesn't know about the files existence it seems to explode.

**Comment by Sam-Costigan** [comment]
I'm assigning you to this David, maybe if we have time we can see about loading players and games from outside of the project folder? Seems kind of inconvenient, but hardly a big problem.

**Comment by thomsedavi** [comment]
I have fixed this but based on what Sam was saying, this might now break it when it project is exported to jar file?

**Comment by thomsedavi** [comment]
No it is all 'g'.

**Comment by Sam-Costigan** [comment]
I've tested this and can't get it to work. Maybe I'm being a dumb dumb, @thomsedavi I'll show you what I tried
